// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces/client.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	gomock "github.com/golang/mock/gomock"
	interfaces "github.com/schwartzmx/gremtune/interfaces"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// HadError mocks base method
func (m *MockClient) HadError() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HadError")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HadError indicates an expected call of HadError
func (mr *MockClientMockRecorder) HadError() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HadError", reflect.TypeOf((*MockClient)(nil).HadError))
}

// Close mocks base method
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// Execute mocks base method
func (m *MockClient) Execute(query string) ([]interfaces.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", query)
	ret0, _ := ret[0].([]interfaces.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute
func (mr *MockClientMockRecorder) Execute(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockClient)(nil).Execute), query)
}

// IsConnected mocks base method
func (m *MockClient) IsConnected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConnected indicates an expected call of IsConnected
func (mr *MockClientMockRecorder) IsConnected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnected", reflect.TypeOf((*MockClient)(nil).IsConnected))
}

// ExecuteAsync mocks base method
func (m *MockClient) ExecuteAsync(query string, responseChannel chan interfaces.AsyncResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteAsync", query, responseChannel)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteAsync indicates an expected call of ExecuteAsync
func (mr *MockClientMockRecorder) ExecuteAsync(query, responseChannel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteAsync", reflect.TypeOf((*MockClient)(nil).ExecuteAsync), query, responseChannel)
}

// ExecuteFileWithBindings mocks base method
func (m *MockClient) ExecuteFileWithBindings(path string, bindings, rebindings map[string]string) ([]interfaces.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteFileWithBindings", path, bindings, rebindings)
	ret0, _ := ret[0].([]interfaces.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteFileWithBindings indicates an expected call of ExecuteFileWithBindings
func (mr *MockClientMockRecorder) ExecuteFileWithBindings(path, bindings, rebindings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteFileWithBindings", reflect.TypeOf((*MockClient)(nil).ExecuteFileWithBindings), path, bindings, rebindings)
}

// ExecuteFile mocks base method
func (m *MockClient) ExecuteFile(path string) ([]interfaces.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteFile", path)
	ret0, _ := ret[0].([]interfaces.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteFile indicates an expected call of ExecuteFile
func (mr *MockClientMockRecorder) ExecuteFile(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteFile", reflect.TypeOf((*MockClient)(nil).ExecuteFile), path)
}

// ExecuteWithBindings mocks base method
func (m *MockClient) ExecuteWithBindings(query string, bindings, rebindings map[string]string) ([]interfaces.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteWithBindings", query, bindings, rebindings)
	ret0, _ := ret[0].([]interfaces.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteWithBindings indicates an expected call of ExecuteWithBindings
func (mr *MockClientMockRecorder) ExecuteWithBindings(query, bindings, rebindings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWithBindings", reflect.TypeOf((*MockClient)(nil).ExecuteWithBindings), query, bindings, rebindings)
}
