{
 "title": "Cosmos DB",
 "description": "Dashboard for the Cosmos DB via Gremlin API",
 "tags": [ "gremcos" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d" }
  ]
 },
 "panels": [
  {
   "title": "Request Charge",
   "type": "graph",
   "description": "Shows request charge information",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gremcos_cosmos_request_charge_per_query",
     "legendFormat": "charge per query"
    },
    {
     "expr": "gremcos_cosmos_request_charge_per_queryresponse_avg",
     "legendFormat": "charge per query response"
    }
   ]
  },
  {
   "title": "Request Charge Total [$interval]",
   "type": "graph",
   "description": "The total request charge over all queries issued so far.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(gremcos_cosmos_request_charge_total[$interval])",
     "legendFormat": "request charge total"
    }
   ]
  },
  {
   "title": "Response Status Code [$interval]",
   "type": "graph",
   "description": "Shows the status codes of the obtained responses within the last $interval.\nThe graph shows the percentage of the occurrence of the specific status code.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gremcos_cosmos_statuscode_total[$interval])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Retry In",
   "type": "graph",
   "description": "This panel shows the suggested waittime of Cosmos DB after which a retry could be issued.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "gremcos_cosmos_retry_after_ms", "legendFormat": "retry in ms" },
    {}
   ]
  },
  {
   "title": "Server Time",
   "type": "graph",
   "description": "Shows the time used on the Cosmos DB side to execute queries.",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "gremcos_cosmos_server_time_per_query_ms",
     "legendFormat": "server time per query"
    },
    {
     "expr": "gremcos_cosmos_server_time_per_queryresponse_avg_ms",
     "legendFormat": "server time per query response"
    }
   ]
  }
 ]
}